name: Publish huayang_oto_vite To Npm

on:
  push:
    branches: [publish-huayangui]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: pnpm install
      - name: Build
        run: npm run build
      - name: "Publish to the npm registry"
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
        